// ─────────────────────────────────────────────
// WORD BANK — 200 words per category, max 12 letters
// ─────────────────────────────────────────────
const CATEGORIES = {
  animals: {
    name: "Animals", icon: "fas fa-paw", unlockAt: 0,
    words: [
      { w: "CAT",       c: "Purring pet"           }, { w: "DOG",       c: "Loyal friend"         },
      { w: "OWL",       c: "Night watcher"         }, { w: "FOX",       c: "Clever canine"        },
      { w: "YAK",       c: "Himalayan ox"          }, { w: "EMU",       c: "Flightless bird"      },
      { w: "COW",       c: "Dairy animal"          }, { w: "HEN",       c: "Laying bird"          },
      { w: "PIG",       c: "Mud lover"             }, { w: "RAM",       c: "Male sheep"           },
      { w: "EWE",       c: "Female sheep"          }, { w: "GNU",       c: "African beast"        },
      { w: "ASS",       c: "Wild donkey"           }, { w: "ELK",       c: "Forest deer"          },
      { w: "JAY",       c: "Bold bird"             }, { w: "ROC",       c: "Mythic bird"          },
      { w: "BEAR",      c: "Forest giant"          }, { w: "WOLF",      c: "Pack hunter"          },
      { w: "DEER",      c: "Gentle grazer"         }, { w: "FROG",      c: "Pond jumper"          },
      { w: "MOLE",      c: "Underground digger"    }, { w: "HARE",      c: "Fast runner"          },
      { w: "LYNX",      c: "Spotted wild cat"      }, { w: "PUMA",      c: "Mountain lion"        },
      { w: "IBIS",      c: "Wading bird"           }, { w: "NEWT",      c: "Tiny amphibian"       },
      { w: "CRAB",      c: "Sidewalk walker"       }, { w: "SWAN",      c: "Graceful swimmer"     },
      { w: "WREN",      c: "Tiny songbird"         }, { w: "TOAD",      c: "Warty hopper"         },
      { w: "MINK",      c: "Fur animal"            }, { w: "VOLE",      c: "Small rodent"         },
      { w: "KITE",      c: "Soaring bird"          }, { w: "DOVE",      c: "Peace symbol"         },
      { w: "CROW",      c: "Smart black bird"      }, { w: "SLUG",      c: "Garden crawler"       },
      { w: "WASP",      c: "Striped stinger"       }, { w: "MOTH",      c: "Night flyer"          },
      { w: "LARK",      c: "Dawn singer"           }, { w: "MULE",      c: "Work animal"          },
      { w: "PONY",      c: "Small horse"           }, { w: "DACE",      c: "River fish"           },
      { w: "BISON",     c: "Prairie giant"         }, { w: "GECKO",     c: "Wall climber"         },
      { w: "HYENA",     c: "Laughing scavenger"    }, { w: "KOALA",     c: "Tree hugger"          },
      { w: "LLAMA",     c: "South American camel"  }, { w: "MOOSE",     c: "Antlered giant"       },
      { w: "OTTER",     c: "River playmate"        }, { w: "QUAIL",     c: "Plump ground bird"    },
      { w: "RAVEN",     c: "Mysterious black bird" }, { w: "SKUNK",     c: "Spray defender"       },
      { w: "TAPIR",     c: "Jungle grazer"         }, { w: "VIPER",     c: "Venomous snake"       },
      { w: "ROBIN",     c: "Red-breasted bird"     }, { w: "FINCH",     c: "Seed eater"           },
      { w: "EGRET",     c: "White wading bird"     }, { w: "HERON",     c: "Tall fisher"          },
      { w: "SWIFT",     c: "Fast flier"            }, { w: "SNAIL",     c: "Shell carrier"        },
      { w: "STOAT",     c: "Agile hunter"          }, { w: "BREAM",     c: "Freshwater fish"      },
      { w: "TROUT",     c: "Spotted swimmer"       }, { w: "PERCH",     c: "River fish"           },
      { w: "CRANE",     c: "Dancing bird"          }, { w: "DINGO",     c: "Wild Aussie dog"      },
      { w: "MORAY",     c: "Reef eel"              }, { w: "MACAW",     c: "Colorful parrot"      },
      { w: "LEMUR",     c: "Big-eyed primate"      }, { w: "PANDA",     c: "Bamboo eater"         },
      { w: "TIGER",     c: "Striped predator"      }, { w: "ZEBRA",     c: "Striped horse"        },
      { w: "EAGLE",     c: "Sky hunter"            }, { w: "SHARK",     c: "Ocean predator"       },
      { w: "WHALE",     c: "Ocean giant"           }, { w: "RHINO",     c: "Horned charger"       },
      { w: "HIPPO",     c: "River horse"           }, { w: "CAMEL",     c: "Desert traveler"      },
      { w: "COBRA",     c: "Hooded snake"          }, { w: "GOOSE",     c: "Honking bird"         },
      { w: "HORSE",     c: "Noble steed"           }, { w: "MOUSE",     c: "Tiny nibbler"         },
      { w: "SNAKE",     c: "Slithering reptile"    }, { w: "SHEEP",     c: "Wool giver"           },
      { w: "SQUID",     c: "Ink shooter"           }, { w: "SLOTH",     c: "Slow climber"         },
      { w: "CHIMP",     c: "Tool user"             }, { w: "SNIPE",     c: "Marshland bird"       },
      { w: "STORK",     c: "Baby bringer"          }, { w: "BADGER",    c: "Burrowing fighter"    },
      { w: "BEAVER",    c: "Dam builder"           }, { w: "DONKEY",    c: "Patient worker"       },
      { w: "FALCON",    c: "Diving hunter"         }, { w: "FERRET",    c: "Curious tunneler"     },
      { w: "GIBBON",    c: "Long-armed swinger"    }, { w: "IGUANA",    c: "Tropical lizard"      },
      { w: "JACKAL",    c: "Desert scavenger"      }, { w: "MAGPIE",    c: "Shiny collector"      },
      { w: "OCELOT",    c: "Spotted wild cat"      }, { w: "PARROT",    c: "Talking bird"         },
      { w: "RABBIT",    c: "Hoppy burrower"        }, { w: "SALMON",    c: "Upstream swimmer"     },
      { w: "TOUCAN",    c: "Big beak bird"         }, { w: "TURTLE",    c: "Shell home"           },
      { w: "WALRUS",    c: "Tusked swimmer"        }, { w: "WEASEL",    c: "Slinky hunter"        },
      { w: "IMPALA",    c: "Leaping antelope"      }, { w: "CONDOR",    c: "Massive soarer"       },
      { w: "COYOTE",    c: "Cunning howler"        }, { w: "LIZARD",    c: "Sun basker"           },
      { w: "MARTEN",    c: "Tree runner"           }, { w: "OSPREY",    c: "Fish hawk"            },
      { w: "POSSUM",    c: "Playing dead"          }, { w: "PUFFIN",    c: "Clown of the sea"     },
      { w: "QUOKKA",    c: "Smiling marsupial"     }, { w: "SPIDER",    c: "Web weaver"           },
      { w: "WOMBAT",    c: "Cube poop maker"       }, { w: "BABOON",    c: "Colorful primate"     },
      { w: "CANARY",    c: "Yellow singer"         }, { w: "CATFISH",   c: "Whiskered swimmer"    },
      { w: "CHEETAH",   c: "Fastest runner"        }, { w: "DOLPHIN",   c: "Playful swimmer"      },
      { w: "GORILLA",   c: "Mighty primate"        }, { w: "HAMSTER",   c: "Cheek stuffer"        },
      { w: "LOBSTER",   c: "Armored crawler"       }, { w: "PANTHER",   c: "Black stalker"        },
      { w: "PEACOCK",   c: "Feather displayer"     }, { w: "PENGUIN",   c: "Tuxedo bird"          },
      { w: "PIRANHA",   c: "Razor-toothed fish"    }, { w: "SCORPION",  c: "Tail stinger"         },
      { w: "SEAHORSE",  c: "Upright swimmer"       }, { w: "STARFISH",  c: "Five-armed drifter"   },
      { w: "SQUIRREL",  c: "Nut hoarder"           }, { w: "ALBATROSS", c: "Longest wingspan"     },
      { w: "CHAMELEON", c: "Color changer"         }, { w: "CROCODILE", c: "Ancient snapper"      },
      { w: "JELLYFISH", c: "Stinging drifter"      }, { w: "ORANGUTAN", c: "Red forest ape"       },
      { w: "SALAMANDER",c: "Fire legend lizard"    }, { w: "STINGRAY",  c: "Flat ocean glider"    },
      { w: "WOLVERINE", c: "Fierce small beast"    }, { w: "NARWHAL",   c: "Sea unicorn"          },
      { w: "PLATYPUS",  c: "Odd-billed mammal"     }, { w: "MANDRILL",  c: "Vivid primate"        },
      { w: "AXOLOTL",   c: "Forever young newt"    }, { w: "HORNBILL",  c: "Large-billed bird"    },
      { w: "CAPYBARA",  c: "Largest rodent"        }, { w: "FLAMINGO",  c: "Pink wader"           },
      { w: "MANATEE",   c: "Sea cow"               }, { w: "MONGOOSE",  c: "Snake fighter"        },
      { w: "MEERKAT",   c: "Desert sentry"         }, { w: "BARNACLE",  c: "Rock clinger"         },
      { w: "STARLING",  c: "Murmur bird"           }, { w: "SWORDFISH", c: "Ocean sword"          },
      { w: "BUMBLEBEE", c: "Fuzzy pollinator"      }, { w: "DRAGONFLY", c: "Wing acrobat"         },
      { w: "FIREFLY",   c: "Living lantern"        }, { w: "CENTIPEDE", c: "Many-legged crawler"  },
      { w: "DHOLE",     c: "Asian wild dog"        }, { w: "SERVAL",    c: "Spotted African cat"  },
      { w: "DUGONG",    c: "Sea grass grazer"      }, { w: "NUMBAT",    c: "Termite hunter"       },
      { w: "FOSSA",     c: "Madagascar predator"   }, { w: "KINKAJOU",  c: "Honey bear"           },
      { w: "QUOLL",     c: "Spotted marsupial"     }, { w: "AARDVARK",  c: "Ant burrower"         },
      { w: "BINTURONG", c: "Bearcat climber"       }, { w: "TAMARIN",   c: "Tiny primate"         },
      { w: "CAIMAN",    c: "Small crocodilian"     }, { w: "LYREBIRD",  c: "Master mimic"         },
      { w: "SUNBIRD",   c: "Tiny nectar sipper"    }, { w: "MUDPUPPY",  c: "Aquatic salamander"   },
      { w: "ALLIGATOR", c: "Armored ambusher"      }, { w: "KINGFISHER",c: "Dive-bombing fisher"  },
      { w: "PORCUPINE", c: "Quill defender"        }, { w: "RHINOCEROS",c: "Armored charger"      },
      { w: "ANGLERFISH",c: "Deep sea lure fish"    }, { w: "ARCHERFISH",c: "Spitting hunter"       },
      { w: "BULLFROG",  c: "Loud pond caller"      }, { w: "BUSHBABY",  c: "Big-eyed leaper"       },
      { w: "CASSOWARY", c: "Dangerous flightless"  }, { w: "CHIPMUNK",  c: "Stripe-backed hoarder" },
      { w: "CUTTLEFISH",c: "Camouflage master"     }, { w: "ECHIDNA",   c: "Spiny egg-layer"       },
      { w: "ELEPHANT",  c: "Largest land animal"   }, { w: "GIRAFFE",   c: "Long-necked grazer"    },
      { w: "HEDGEHOG",  c: "Spiny garden visitor"  }, { w: "JAGUAR",    c: "Spotted jungle cat"    },
      { w: "KANGAROO",  c: "Pouch carrying hopper" }, { w: "LEOPARD",   c: "Rosette-spotted cat"   },
      { w: "LION",      c: "Pride leader"          }, { w: "NIGHTHAWK", c: "Twilight aerial hunter" },
      { w: "PANGOLIN",  c: "Scaled anteater"       }, { w: "PELICAN",   c: "Pouch-billed diver"    },
      { w: "PIGEON",    c: "Urban navigator"       }, { w: "REINDEER",  c: "Arctic gift bringer"   },
      { w: "ROADRUNNER",c: "Fast desert bird"      }, { w: "SEALION",   c: "Playful circus star"   },
      { w: "TAPEWORM",  c: "Ribbon parasite"       }, { w: "SUNFISH",   c: "Flat ocean giant"      },
    ],
  },

  nature: {
    name: "Nature", icon: "fas fa-mountain", unlockAt: 15,
    words: [
      { w: "OAK",       c: "Strong tree"           }, { w: "DEW",       c: "Morning drops"        },
      { w: "ICE",       c: "Frozen water"          }, { w: "BOG",       c: "Wet ground"           },
      { w: "ELM",       c: "Tall shade tree"       }, { w: "FEN",       c: "Marshy ground"        },
      { w: "ASH",       c: "Grey-barked tree"      }, { w: "SOD",       c: "Grass layer"          },
      { w: "CLAY",      c: "Sticky soil"           }, { w: "DUNE",      c: "Sand hill"            },
      { w: "FERN",      c: "Forest frond"          }, { w: "GLEN",      c: "Narrow valley"        },
      { w: "HILL",      c: "Gentle rise"           }, { w: "ISLE",      c: "Small island"         },
      { w: "KELP",      c: "Sea forest"            }, { w: "LAKE",      c: "Still water"          },
      { w: "LAVA",      c: "Molten rock"           }, { w: "LEAF",      c: "Green panel"          },
      { w: "MESA",      c: "Flat-topped hill"      }, { w: "MIST",      c: "Soft fog"             },
      { w: "MOOR",      c: "Open highland"         }, { w: "MOSS",      c: "Velvet ground"        },
      { w: "PEAT",      c: "Ancient bog matter"    }, { w: "PINE",      c: "Evergreen tree"       },
      { w: "POND",      c: "Small still water"     }, { w: "REEF",      c: "Coral wall"           },
      { w: "RIFT",      c: "Ground crack"          }, { w: "ROCK",      c: "Solid ground"         },
      { w: "ROSE",      c: "Thorned beauty"        }, { w: "RUSH",      c: "Water reed"           },
      { w: "SAND",      c: "Fine grains"           }, { w: "SEED",      c: "Plant start"          },
      { w: "SNOW",      c: "Frozen flakes"         }, { w: "SOIL",      c: "Dark earth"           },
      { w: "STEM",      c: "Plant stalk"           }, { w: "TIDE",      c: "Sea rise and fall"    },
      { w: "VALE",      c: "Broad valley"          }, { w: "VINE",      c: "Climbing plant"       },
      { w: "WAVE",      c: "Water swell"           }, { w: "WEED",      c: "Wild plant"           },
      { w: "WIND",      c: "Moving air"            }, { w: "WOOD",      c: "Forest stand"         },
      { w: "BIRCH",     c: "White-barked tree"     }, { w: "BROOK",     c: "Babbling stream"      },
      { w: "CEDAR",     c: "Aromatic wood"         }, { w: "CLIFF",     c: "Steep rock face"      },
      { w: "CORAL",     c: "Ocean builder"         }, { w: "CREEK",     c: "Narrow stream"        },
      { w: "DELTA",     c: "River mouth fan"       }, { w: "FIELD",     c: "Open farmland"        },
      { w: "FJORD",     c: "Glacial inlet"         }, { w: "FLAME",     c: "Dancing fire"         },
      { w: "FLORA",     c: "Plant life"            }, { w: "FLINT",     c: "Fire stone"           },
      { w: "FLOOD",     c: "Overflow of water"     }, { w: "FROST",     c: "Ice coating"          },
      { w: "GLADE",     c: "Forest clearing"       }, { w: "GORGE",     c: "Deep ravine"          },
      { w: "GROVE",     c: "Tree cluster"          }, { w: "GULCH",     c: "Rocky channel"        },
      { w: "MARSH",     c: "Waterlogged land"      }, { w: "OCEAN",     c: "Vast water"           },
      { w: "PLAIN",     c: "Flat open land"        }, { w: "RIDGE",     c: "Long hill top"        },
      { w: "RIVER",     c: "Flowing water"         }, { w: "ROOTS",     c: "Underground anchor"   },
      { w: "SHRUB",     c: "Low bush"              }, { w: "SLOPE",     c: "Angled ground"        },
      { w: "SPORE",     c: "Tiny plant seed"       }, { w: "STONE",     c: "Hard mineral"         },
      { w: "STORM",     c: "Wild weather"          }, { w: "SWAMP",     c: "Murky wetland"        },
      { w: "THORN",     c: "Sharp plant spike"     }, { w: "TRAIL",     c: "Forest path"          },
      { w: "TRUNK",     c: "Tree body"             }, { w: "TUNDRA",    c: "Frozen plain"         },
      { w: "VALLEY",    c: "Between two hills"     }, { w: "CANOPY",    c: "Forest roof"          },
      { w: "CAVERN",    c: "Dark hollow"           }, { w: "CINDER",    c: "Burnt rock"           },
      { w: "COBBLE",    c: "Rounded stone"         }, { w: "DESERT",    c: "Dry wasteland"        },
      { w: "ESTUARY",   c: "River meets sea"       }, { w: "FUNGUS",    c: "Spore grower"         },
      { w: "GEYSER",    c: "Hot spring spout"      }, { w: "GLACIER",   c: "Slow ice river"       },
      { w: "GRANITE",   c: "Hard grey rock"        }, { w: "GRAVEL",    c: "Small stones"         },
      { w: "HABITAT",   c: "Animal home zone"      }, { w: "ICEBERG",   c: "Floating ice mass"    },
      { w: "JUNGLE",    c: "Dense wild forest"     }, { w: "LAGOON",    c: "Shallow sea pool"     },
      { w: "LICHEN",    c: "Rock surface life"     }, { w: "MANTLE",    c: "Earth inner layer"    },
      { w: "MEADOW",    c: "Flowering grassland"   }, { w: "MINERAL",   c: "Natural earth solid"  },
      { w: "PEBBLE",    c: "Smooth small stone"    }, { w: "PLATEAU",   c: "High flat land"       },
      { w: "POLLEN",    c: "Flower dust"           }, { w: "RAPIDS",    c: "White water rush"     },
      { w: "RAVINE",    c: "Deep narrow gap"       }, { w: "REDWOOD",   c: "Tallest tree"         },
      { w: "SAVANNA",   c: "Grassy open plain"     }, { w: "SEAWEED",   c: "Ocean plant"          },
      { w: "SPRING",    c: "Water from earth"      }, { w: "THICKET",   c: "Dense bush tangle"    },
      { w: "TORRENT",   c: "Rushing water"         }, { w: "TROPICS",   c: "Hot wet zone"         },
      { w: "VOLCANO",   c: "Fire mountain"         }, { w: "WETLAND",   c: "Soggy earth zone"     },
      { w: "WOODLAND",  c: "Tree-filled land"      }, { w: "BEDROCK",   c: "Deepest solid layer"  },
      { w: "BIOME",     c: "Life zone"             }, { w: "BLIZZARD",  c: "Snow storm"           },
      { w: "BOULDER",   c: "Large round rock"      }, { w: "CARBON",    c: "Life building block"  },
      { w: "CYCLONE",   c: "Spinning storm"        }, { w: "DRIFTWOOD", c: "Ocean-worn log"       },
      { w: "EARTHWORM", c: "Soil tunneler"         }, { w: "FOSSIL",    c: "Ancient life stone"   },
      { w: "GEODE",     c: "Crystal hollow rock"   }, { w: "GUST",      c: "Sudden wind burst"    },
      { w: "HEATH",     c: "Open shrub land"       }, { w: "HUMUS",     c: "Rich dark soil"       },
      { w: "ISTHMUS",   c: "Land bridge"           }, { w: "KARST",     c: "Limestone landscape"  },
      { w: "KNOLL",     c: "Small round hill"      }, { w: "LOAM",      c: "Fertile mixed soil"   },
      { w: "MAGMA",     c: "Underground lava"      }, { w: "NIMBUS",    c: "Rain cloud"           },
      { w: "OXBOW",     c: "Curved river bend"     }, { w: "PRAIRIE",   c: "Vast grass plain"     },
      { w: "PUMICE",    c: "Light volcanic rock"   }, { w: "QUARTZ",    c: "Crystal mineral"      },
      { w: "RUNOFF",    c: "Rain flowing away"     }, { w: "SCARP",     c: "Steep slope face"     },
      { w: "SEDIMENT",  c: "Settled particles"     }, { w: "SHALE",     c: "Layered rock"         },
      { w: "STRATA",    c: "Rock layer bands"      }, { w: "TAIGA",     c: "Cold forest belt"     },
      { w: "TERRACE",   c: "Stepped hillside"      }, { w: "TSUNAMI",   c: "Ocean wave surge"     },
      { w: "UPDRAFT",   c: "Rising warm air"       }, { w: "VORTEX",    c: "Spinning air mass"    },
      { w: "WATERSHED", c: "Drainage divide"       }, { w: "SINKHOLE",  c: "Ground collapse"      },
      { w: "MUDFLAT",   c: "Tidal mud shore"       }, { w: "EROSION",   c: "Wearing away"         },
      { w: "CIRQUE",    c: "Glacial bowl"          }, { w: "VERDANT",   c: "Lush and green"       },
      { w: "WILDERNESS",c: "Untamed wild land"     }, { w: "WATERFALL", c: "Plunging river"       },
      { w: "STALACTITE",c: "Hanging cave rock"     }, { w: "PERMAFROST",c: "Always frozen ground" },
      { w: "UNDERGROWTH",c:"Forest floor plants"   }, { w: "ALLUVIAL",  c: "River deposit soil"   },
      { w: "BASALT",    c: "Dark volcanic rock"    }, { w: "CANYON",    c: "Deep river-cut gorge" },
      { w: "CHAPARRAL", c: "Dry shrubland"         }, { w: "CONIFER",   c: "Cone-bearing tree"    },
      { w: "COPSE",     c: "Small woodland"        }, { w: "DORMANT",   c: "Sleeping volcano"     },
      { w: "ESKER",     c: "Glacial gravel ridge"  }, { w: "FISSURE",   c: "Deep rock crack"      },
      { w: "FOLIAGE",   c: "Plant leaf mass"       }, { w: "FOOTHILL",  c: "Mountain base slope"  },
      { w: "HARDWOOD",  c: "Dense broadleaf tree"  }, { w: "HEADLAND",  c: "Coastal cliff point"  },
      { w: "LANDSLIDE", c: "Slope collapse"        }, { w: "LOWLAND",   c: "Flat terrain below"   },
      { w: "MARSHLAND", c: "Waterlogged area"      }, { w: "MORAINE",   c: "Glacial rock deposit" },
      { w: "OUTCROP",   c: "Rock emerging from soil"}, { w: "PETRIFIED", c: "Turned to stone"     },
      { w: "RAINFOREST",c: "Tropical wet forest"   }, { w: "RIVERBANK", c: "Stream edge ground"   },
      { w: "SALTMARSH", c: "Coastal saline wetland" }, { w: "SANDSTONE", c: "Compressed sand rock" },
      { w: "SCREE",     c: "Loose slope stones"    }, { w: "SEDGE",     c: "Grasslike marsh plant"},
      { w: "SHOAL",     c: "Shallow water bank"    }, { w: "SOFTWOOD",  c: "Conifer light wood"   },
      { w: "SPHAGNUM",  c: "Bog-forming moss"      }, { w: "SAPWOOD",   c: "Outer tree wood"      },
      { w: "LANDMASS",  c: "Large continental area" }, { w: "HOTSPRING",  c: "Geothermal water"    },
      { w: "HINTERLAND",c: "Remote inland region"  }, { w: "OVERHANG",  c: "Rock jutting outward" },
      { w: "TURF",      c: "Surface grass layer"   }, { w: "BRINE",     c: "Very salty water"     },
      { w: "COPPICE",   c: "Managed woodland"      }, { w: "CREVASSE",  c: "Deep glacier crack"   },
      { w: "DEADWOOD",  c: "Fallen tree debris"    }, { w: "DOWNPOUR",  c: "Heavy rain burst"     },
      { w: "FLOODPLAIN",c: "River overflow flat"   }, { w: "FOOTHILLS", c: "Mountains base area"  },
      { w: "FORESHORE", c: "Between tide marks"    }, { w: "FRESHWATER",c: "Non-salt inland water" },
      { w: "GROUNDWATER",c:"Below surface water"   }, { w: "HIGHWATER", c: "Peak flood level"     },
    ],
  },

  cosmos: {
    name: "Cosmos", icon: "fas fa-star", unlockAt: 30,
    words: [
      { w: "SUN",       c: "Our star"              }, { w: "ION",       c: "Charged atom"         },
      { w: "ORB",       c: "Spherical body"        }, { w: "RAY",       c: "Light beam"           },
      { w: "GAS",       c: "Diffuse matter"        }, { w: "STAR",      c: "Burning ball"         },
      { w: "MARS",      c: "Red planet"            }, { w: "MOON",      c: "Earth's companion"    },
      { w: "HALO",      c: "Light ring"            }, { w: "NOVA",      c: "Stellar burst"        },
      { w: "ATOM",      c: "Tiny matter unit"      }, { w: "AEON",      c: "Vast time span"       },
      { w: "AXIS",      c: "Spinning center"       }, { w: "BELT",      c: "Orbital band"         },
      { w: "CORE",      c: "Innermost part"        }, { w: "DARK",      c: "Unlit expanse"        },
      { w: "DISC",      c: "Flat spiral shape"     }, { w: "DUST",      c: "Cosmic particles"     },
      { w: "FLUX",      c: "Constant change"       }, { w: "HAZE",      c: "Diffuse glow"         },
      { w: "HEAT",      c: "Radiation form"        }, { w: "HOLE",      c: "Gravity well"         },
      { w: "MASS",      c: "Matter amount"         }, { w: "NODE",      c: "Connection point"     },
      { w: "VOID",      c: "Empty space"           }, { w: "WAVE",      c: "Energy ripple"        },
      { w: "ZONE",      c: "Defined space band"    }, { w: "COMET",     c: "Icy wanderer"         },
      { w: "DWARF",     c: "Small star"            }, { w: "EPOCH",     c: "Cosmic time period"   },
      { w: "FLARE",     c: "Solar explosion"       }, { w: "GIANT",     c: "Massive star class"   },
      { w: "LUNAR",     c: "Moon related"          }, { w: "NEBULA",    c: "Star nursery cloud"   },
      { w: "NIGHT",     c: "Dark sky time"         }, { w: "ORBIT",     c: "Curved path"          },
      { w: "PHASE",     c: "Moon cycle step"       }, { w: "PLUTO",     c: "Dwarf planet"         },
      { w: "PROBE",     c: "Space explorer"        }, { w: "PULSE",     c: "Energy beat"          },
      { w: "QUARK",     c: "Subatomic particle"    }, { w: "RADIO",     c: "Wave emission"        },
      { w: "REALM",     c: "Cosmic domain"         }, { w: "ROVER",     c: "Planet explorer"      },
      { w: "SOLAR",     c: "Sun-powered"           }, { w: "SPACE",     c: "Infinite beyond"      },
      { w: "BURST",     c: "Gamma ray event"       }, { w: "AURORA",    c: "Polar light show"     },
      { w: "BINARY",    c: "Twin star system"      }, { w: "CLUSTER",   c: "Star grouping"        },
      { w: "CORONA",    c: "Sun's outer ring"      }, { w: "COSMOS",    c: "All that exists"      },
      { w: "CRATER",    c: "Impact bowl"           }, { w: "ECLIPSE",   c: "Shadow crossing"      },
      { w: "ENERGY",    c: "Force carrier"         }, { w: "ENTROPY",   c: "Cosmic disorder"      },
      { w: "EQUINOX",   c: "Equal light day"       }, { w: "EUROPA",    c: "Icy Jupiter moon"     },
      { w: "FISSION",   c: "Atom splitting"        }, { w: "FUSION",    c: "Stars energy source"  },
      { w: "GALAXY",    c: "Star city"             }, { w: "GANYMEDE",  c: "Largest moon"         },
      { w: "GRAVITY",   c: "Pulling force"         }, { w: "HORIZON",   c: "Event boundary"       },
      { w: "IMPACT",    c: "Collision event"       }, { w: "JOVIAN",    c: "Jupiter-like"         },
      { w: "JUPITER",   c: "Largest planet"        }, { w: "KEPLER",    c: "Orbit law giver"      },
      { w: "KUIPER",    c: "Outer belt zone"       }, { w: "LANDER",    c: "Surface craft"        },
      { w: "LAUNCH",    c: "Rocket liftoff"        }, { w: "LENSING",   c: "Light bent by mass"   },
      { w: "MERCURY",   c: "Innermost planet"      }, { w: "METEOR",    c: "Shooting streak"      },
      { w: "MILKY",     c: "Our galaxy arm"        }, { w: "MISSION",   c: "Space journey"        },
      { w: "NEUTRON",   c: "Dense star remnant"    }, { w: "NUCLEUS",   c: "Atom center"          },
      { w: "OPACITY",   c: "Light blocking"        }, { w: "OZONE",     c: "Atmospheric shield"   },
      { w: "PHOTON",    c: "Light particle"        }, { w: "PLANET",    c: "Orbiting world"       },
      { w: "PLASMA",    c: "Ionized gas state"     }, { w: "PULSAR",    c: "Spinning neutron star" },
      { w: "QUASAR",    c: "Bright galactic core"  }, { w: "REDSHIFT",  c: "Galaxy moving away"   },
      { w: "REFRACT",   c: "Light bending"         }, { w: "SATURN",    c: "Ringed beauty"        },
      { w: "SOLSTICE",  c: "Sun at extreme"        }, { w: "SPECTRUM",  c: "Light color range"    },
      { w: "SUPERNOVA", c: "Stellar explosion"     }, { w: "TITAN",     c: "Saturn giant moon"    },
      { w: "TRANSIT",   c: "Planet crossing"       }, { w: "UMBRA",     c: "Darkest shadow"       },
      { w: "URANUS",    c: "Tilted ice giant"      }, { w: "VACUUM",    c: "Airless space"        },
      { w: "VENUS",     c: "Hottest planet"        }, { w: "WORMHOLE",  c: "Space time tunnel"    },
      { w: "ZENITH",    c: "Highest sky point"     }, { w: "ZODIAC",    c: "Star sign belt"       },
      { w: "PERIHELION",c: "Closest sun point"     }, { w: "APHELION",  c: "Farthest sun point"   },
      { w: "ACCRETION", c: "Matter gathering"      }, { w: "MAGNETAR",  c: "Magnetic neutron star" },
      { w: "PARALLAX",  c: "Distance by angle"     }, { w: "PROTOSTAR", c: "Star being born"      },
      { w: "ANDROMEDA", c: "Nearest galaxy"        }, { w: "ASTEROID",  c: "Rocky space body"     },
      { w: "SUBLIMATE", c: "Ice to gas direct"     }, { w: "TERMINATOR",c: "Day-night line"       },
      { w: "OBLATE",    c: "Flattened sphere"      }, { w: "RADIANT",   c: "Meteor source point"  },
      { w: "REFLECT",   c: "Light bouncing off"    }, { w: "INFLATE",   c: "Universe expansion"   },
      { w: "RINGED",    c: "Saturn-like"           }, { w: "ROCKY",     c: "Solid planet type"    },
      { w: "SCARP",     c: "Crater wall"           }, { w: "SPEED",     c: "Velocity measure"     },
      { w: "XENON",     c: "Noble gas element"     }, { w: "HUBBLE",    c: "Space telescope"      },
      { w: "LAGRANGE",  c: "Gravity balance point" }, { w: "PHOTOSPHERE",c:"Sun visible surface"  },
      { w: "SINGULARITY",c:"Black hole center"     }, { w: "CELESTIAL", c: "Of the sky"           },
      { w: "TIDAL",     c: "Gravity stretching"    }, { w: "COSMIC",    c: "Of the universe"      },
      { w: "DENSE",     c: "Tightly packed matter" }, { w: "FIELD",     c: "Force region"         },
      { w: "FOCUS",     c: "Lens point"            }, { w: "GLOW",      c: "Faint light emission" },
      { w: "HOTSPOT",   c: "Volcanic island source" }, { w: "INERTIA",  c: "Resistance to motion" },
      { w: "LIMB",      c: "Star or moon edge"     }, { w: "NADIR",     c: "Lowest sky point"     },
      { w: "PENUMBRA",  c: "Partial shadow region" }, { w: "PERIGEE",   c: "Closest orbit point"   },
      { w: "RADIAN",    c: "Angle measure unit"    }, { w: "SCALAR",    c: "Magnitude only value" },
      { w: "THERMAL",   c: "Heat-based energy"     }, { w: "TORQUE",    c: "Rotational force"     },
      { w: "VECTOR",    c: "Direction and force"   }, { w: "VERNAL",    c: "Spring equinox"       },
      { w: "ALBEDO",    c: "Surface reflectivity"  }, { w: "APOGEE",    c: "Farthest orbit point" },
      { w: "BOLIDE",    c: "Exploding fireball"    }, { w: "BOSON",     c: "Force carrier particle"},
      { w: "CHROMOSPHERE",c:"Sun middle layer"     }, { w: "COMA",      c: "Comet gas cloud"       },
      { w: "CONJUNCTION",c:"Planets aligned view"  }, { w: "DEBRIS",    c: "Space rock fragments"  },
      { w: "DECLINATION",c:"Star angle north south"},{ w: "DOPPLER",   c: "Wave frequency shift"  },
      { w: "DYNAMO",    c: "Magnetic field engine" }, { w: "EJECTA",    c: "Impact thrown material"},
      { w: "ELONGATION",c:"Planet angle from sun"  }, { w: "EXOPLANET", c: "Planet beyond our sun" },
      { w: "FERMION",   c: "Matter particle type"  }, { w: "FILAMENT",  c: "Plasma thread on sun"  },
      { w: "FLYBY",     c: "Spacecraft close pass" }, { w: "GEODESIC",  c: "Curved spacetime path" },
      { w: "GEODESY",   c: "Earth shape measuring" }, { w: "GRABEN",    c: "Sunken crustal block"  },
      { w: "GRAZING",   c: "Near-miss orbit"       }, { w: "HELIOPAUSE",c:"Solar wind boundary"   },
      { w: "HELIOSPHERE",c:"Sun influence zone"    }, { w: "INFRARED",  c: "Heat radiation wave"   },
      { w: "INTERCEPT", c: "Orbit path crossing"   }, { w: "IONOSPHERE",c:"Charged upper air"     },
      { w: "KILOPARSEC",c:"Thousand parsec unit"   }, { w: "LAGOON",    c: "Emission nebula type"  },
      { w: "MAGNITUDE", c: "Star brightness scale" }, { w: "MANTLE",    c: "Planet middle layer"   },
      { w: "MERIDIAN",  c: "Sky longitude line"    }, { w: "MOONRISE",  c: "Moon above horizon"    },
      { w: "MOONSET",   c: "Moon below horizon"    }, { w: "NEBULOSITY",c:"Cloudy space region"   },
      { w: "NEUTRINO",  c: "Ghostly particle"      }, { w: "OCCULTATION",c:"Star hidden by body"  },
      { w: "OORT",      c: "Far comet cloud zone"  }, { w: "PARSEC",    c: "Stellar distance unit" },
      { w: "APASTRON",  c: "Farthest binary point"  }, { w: "PERIAPSIS", c: "Closest orbit approach" },
      { w: "PHOTOMETRY",c:"Measuring star light"   }, { w: "PRECESSION",c:"Axis slow wobble"      },
      { w: "PROMINENCE",c:"Solar gas eruption"     }, { w: "PROPULSION",c:"Rocket thrust system"  },
      { w: "QUADRANT",  c: "Sky quarter section"   }, { w: "QUIESCENT", c: "Calm low-activity star"},
      { w: "REDGIANT",  c: "Expanding old star"    }, { w: "REENTRY",   c: "Returning to atmosphere"},
      { w: "RELATIVITY",c:"Space time theory"      }, { w: "RESONANCE", c: "Orbital timing lock"   },
      { w: "RETROGRADE",c:"Backward planet motion" }, { w: "REVOLUTION",c:"One orbit completion"  },
      { w: "ROTATION",  c: "Spinning on axis"      }, { w: "SATELLITE", c: "Orbiting body"         },
      { w: "SCATTERED", c: "Outer solar region"    }, { w: "SIDEREAL",  c: "Star-based time"       },
      { w: "SKYMAP",    c: "Star chart"            }, { w: "SOLARNOON", c: "Sun at highest point"  },
    ],
  },

  zen: {
    name: "Zen", icon: "fas fa-yin-yang", unlockAt: 45,
    words: [
      { w: "OM",        c: "Sacred sound"          }, { w: "TAO",       c: "The way"              },
      { w: "CHI",       c: "Life energy"           }, { w: "QI",        c: "Vital force"          },
      { w: "ZEN",       c: "Present mind"          }, { w: "AUM",       c: "Cosmic hum"           },
      { w: "WU",        c: "Non-being"             }, { w: "DO",        c: "Path of discipline"   },
      { w: "MA",        c: "Negative space"        }, { w: "WA",        c: "Japanese harmony"     },
      { w: "FLOW",      c: "Effortless state"      }, { w: "CALM",      c: "Stilled mind"         },
      { w: "DEEP",      c: "Unfathomable peace"    }, { w: "EASE",      c: "Natural effortlessness"},
      { w: "FEEL",      c: "Inner sensing"         }, { w: "FREE",      c: "Liberated state"      },
      { w: "HUSH",      c: "Deep quiet"            }, { w: "KEEN",      c: "Sharp awareness"      },
      { w: "LULL",      c: "Gentle stillness"      }, { w: "MILD",      c: "Gentle disposition"   },
      { w: "OPEN",      c: "Receptive state"       }, { w: "PURE",      c: "Uncontaminated mind"  },
      { w: "REST",      c: "Renewal state"         }, { w: "SAGE",      c: "Wise one"             },
      { w: "SEED",      c: "Potential within"      }, { w: "SLOW",      c: "Unhurried pace"       },
      { w: "SOFT",      c: "Gentle touch"          }, { w: "SOUL",      c: "Inner essence"        },
      { w: "STILL",     c: "Motionless presence"   }, { w: "TRUE",      c: "Authentic being"      },
      { w: "VOID",      c: "Space of all things"   }, { w: "WAKE",      c: "Conscious arising"    },
      { w: "WARM",      c: "Open-hearted"          }, { w: "WHOLE",     c: "Complete in self"     },
      { w: "WISE",      c: "Knowing without words" }, { w: "GAZE",      c: "Soft awareness"       },
      { w: "AWARE",     c: "Conscious presence"    }, { w: "BEING",     c: "Pure existence"       },
      { w: "BLISS",     c: "Uncaused joy"          }, { w: "BREATH",    c: "Anchor to now"        },
      { w: "CLEAR",     c: "Uncluttered mind"      }, { w: "DWELL",     c: "Resting in being"     },
      { w: "EMPTY",     c: "Full of potential"     }, { w: "FOCUS",     c: "Single pointed mind"  },
      { w: "GRACE",     c: "Effortless beauty"     }, { w: "INNER",     c: "Interior world"       },
      { w: "KARMA",     c: "Cause and effect"      }, { w: "LIGHT",     c: "Clarity of mind"      },
      { w: "LOTUS",     c: "Rising from mud"       }, { w: "PEACE",     c: "Undisturbed state"    },
      { w: "PRANA",     c: "Breath energy"         }, { w: "QUIET",     c: "Absence of noise"     },
      { w: "RELAX",     c: "Releasing tension"     }, { w: "SENSE",     c: "Acute perception"     },
      { w: "SMILE",     c: "Inner contentment"     }, { w: "SPACE",     c: "Between thoughts"     },
      { w: "TRUST",     c: "Faith in flow"         }, { w: "UNION",     c: "Oneness of self"      },
      { w: "UNITY",     c: "All is connected"      }, { w: "WATCH",     c: "Silent observer"      },
      { w: "YIELD",     c: "Surrendering ego"      }, { w: "ANCHOR",    c: "Grounding point"      },
      { w: "ATTEND",    c: "Full presence"         }, { w: "CENTRE",    c: "Where all meets"      },
      { w: "DHARMA",    c: "Your true path"        }, { w: "GROUND",    c: "Stable foundation"    },
      { w: "MANTRA",    c: "Sacred repetition"     }, { w: "MINDFUL",   c: "Awake to now"         },
      { w: "MUDRA",     c: "Sacred hand gesture"   }, { w: "NATURE",    c: "Original self"        },
      { w: "REFUGE",    c: "Safe inner place"      }, { w: "RENEW",     c: "Begin again freshly"  },
      { w: "RITUAL",    c: "Repeated sacred act"   }, { w: "SAMADHI",   c: "Deep meditation"      },
      { w: "SERENE",    c: "Untroubled calm"       }, { w: "SHADOW",    c: "Unacknowledged self"  },
      { w: "SIDDHI",    c: "Spiritual power"       }, { w: "SILENCE",   c: "Space without sound"  },
      { w: "SIMPLE",    c: "Free of complexity"    }, { w: "SUTRA",     c: "Ancient truth thread" },
      { w: "WONDER",    c: "Child-like openness"   }, { w: "WUWEI",     c: "Non-action action"    },
      { w: "AHIMSA",    c: "Non-violence"          }, { w: "ANANDA",    c: "Pure bliss state"     },
      { w: "ANICCA",    c: "Impermanence"          }, { w: "ATMAN",     c: "True inner self"      },
      { w: "BODHI",     c: "Awakening tree"        }, { w: "BRAHMA",    c: "Creative force"       },
      { w: "BUDDHA",    c: "The awakened one"      }, { w: "EQUANIMITY",c: "Balanced mind"        },
      { w: "GRATITUDE", c: "Thankful heart"        }, { w: "INSIGHT",   c: "Clear inner seeing"   },
      { w: "INTENTION", c: "Conscious purpose"     }, { w: "KENSHO",    c: "Brief awakening"      },
      { w: "KINHIN",    c: "Walking meditation"    }, { w: "MINDSET",   c: "Mental orientation"   },
      { w: "MOKSHA",    c: "Liberation from cycle" }, { w: "NIRVANA",   c: "Flame extinguished"   },
      { w: "ONENESS",   c: "No separation"         }, { w: "PRAJNA",    c: "Transcendent wisdom"  },
      { w: "PRESENCE",  c: "Being fully here"      }, { w: "RELEASE",   c: "Letting go fully"     },
      { w: "SANGHA",    c: "Spiritual community"   }, { w: "SATORI",    c: "Sudden awakening"     },
      { w: "SERENITY",  c: "Lasting inner calm"    }, { w: "SHANTI",    c: "Peace chant"          },
      { w: "SITTING",   c: "Still meditation"      }, { w: "SOLITUDE",  c: "Alone with self"      },
      { w: "TANTRA",    c: "Sacred energy weaving" }, { w: "VIPASSANA", c: "Insight meditation"   },
      { w: "WHOLENESS", c: "Nothing is missing"    }, { w: "ZAZEN",     c: "Seated Zen practice"  },
      { w: "ZENSHIN",   c: "Full body mind"        }, { w: "ZENDO",     c: "Zen practice hall"    },
      { w: "KOANS",     c: "Mind-breaking riddles" }, { w: "OBSERVE",   c: "Witness without judging"},
      { w: "SUCHNESS",  c: "Things as they are"    }, { w: "WAKEFULNESS",c:"Ongoing awareness"    },
      { w: "OPENNESS",  c: "Unguarded reception"   }, { w: "RADIANCE",  c: "Inner light shining"  },
      { w: "SURRENDER", c: "Releasing control"     }, { w: "HARMONY",   c: "Balanced coexistence" },
      { w: "DEVOTION",  c: "Heartfelt dedication"  }, { w: "PATIENCE",  c: "Waiting without want" },
      { w: "COURAGE",   c: "Acting despite fear"   }, { w: "CLARITY",   c: "Seeing without fog"   },
      { w: "NONDUAL",   c: "No separation seen"    }, { w: "ABIDING",   c: "Resting in truth"     },
      { w: "LETTING",   c: "Not holding on"        }, { w: "FLOWING",   c: "Moving without force" },
      { w: "MERGING",   c: "Boundaries dissolving" }, { w: "PRISTINE",  c: "Unspoiled awareness"  },
      { w: "RESTING",   c: "Being without doing"   }, { w: "SPACIOUS",  c: "Wide open awareness"  },
      { w: "TRUSTING",  c: "Faith in the process"  }, { w: "UNFOLDING", c: "Natural revealing"    },
      { w: "ABLAZE",    c: "Inner fire lit"        }, { w: "ACCEPT",    c: "Welcoming what is"    },
      { w: "ALIGNED",   c: "Body mind united"      }, { w: "ALLOW",     c: "Not resisting flow"   },
      { w: "ASCEND",    c: "Rising awareness"      }, { w: "AWAKEN",    c: "Coming to see"        },
      { w: "BALANCED",  c: "Neither pulled nor pushed"}, { w: "BENEVOLENCE",c:"Goodwill toward all"},
      { w: "BOUNDLESS", c: "No inner edge"         }, { w: "BREATHING", c: "Conscious respiration"},
      { w: "CENTERING", c: "Returning to still"    }, { w: "CHOSEN",    c: "Deliberate intention" },
      { w: "CLEANSING", c: "Releasing old weight"  }, { w: "COMPLETE",  c: "Nothing to add"       },
      { w: "CONSCIOUS", c: "Fully awake to life"   }, { w: "CONSTANT",  c: "Never wavering"       },
      { w: "CONTENT",   c: "At peace with now"     }, { w: "CONTINUAL", c: "Unbroken awareness"   },
      { w: "CREATIVE",  c: "Born from inner still" }, { w: "DEDICATE",  c: "Fully committing"     },
      { w: "DETACHED",  c: "Not clinging to forms" }, { w: "DISCERN",   c: "Wise discrimination"  },
      { w: "DISSOLVE",  c: "Ego falling away"      }, { w: "EMBRACE",   c: "Holding all gently"   },
      { w: "ENDURE",    c: "Sitting through storm" }, { w: "EQUABLE",   c: "Consistent inner calm" },
      { w: "ESSENCE",   c: "Core without form"     }, { w: "ETERNAL",   c: "Beyond time"          },
      { w: "EXPAND",    c: "Awareness growing wide"},{ w: "FORMLESS",  c: "Without fixed shape"  },
      { w: "GENUINE",   c: "Authentic expression"  }, { w: "GUIDANCE",  c: "Inner compass"        },
      { w: "HEALING",   c: "Returning to whole"    }, { w: "HUMBLE",    c: "Small before vastness" },
      { w: "INFINITE",  c: "No beginning or end"   }, { w: "INSPIRED",  c: "Breath flowing in"    },
      { w: "INTEGRAL",  c: "All parts in order"    }, { w: "KNOWING",   c: "Pre-conceptual truth"  },
      { w: "LIBERATING",c: "Freeing from bondage"  }, { w: "LIMITLESS", c: "No boundary of self"  },
      { w: "LISTENING", c: "Silent deep hearing"   }, { w: "LUMINOUS",  c: "Inner light shining"  },
      { w: "MEDITATE",  c: "Sitting in stillness"  }, { w: "MINDSCAPE", c: "Interior mental view" },
      { w: "NAMASTE",   c: "Light in me sees you"  }, { w: "NONDOING",  c: "Acting through being" },
      { w: "NOTICING",  c: "Gentle observation"    }, { w: "PROFOUND",  c: "Deeply resonant truth" },
      { w: "RECEPTIVE", c: "Open to receive"       }, { w: "RETURNING", c: "Coming back to source" },
      { w: "REVERENCE", c: "Deep sacred respect"   }, { w: "RIPENING",  c: "Growing toward fullness"},
      { w: "ROOTED",    c: "Deeply grounded"       }, { w: "SACRED",    c: "Holy in nature"       },
      { w: "SADHANA",   c: "Daily spiritual practice"}, { w: "SHEDDING", c: "Releasing what passed"},
      { w: "SHINING",   c: "Inner light expressed" }, { w: "SIMPLIFY",  c: "Remove the excess"    },
      { w: "SOAKING",   c: "Absorbing deeply"      }, { w: "SOFTENING", c: "Releasing hardness"   },
      { w: "SOURCING",  c: "Finding the root"      }, { w: "SPARKLING", c: "Alive with presence"  },
      { w: "STEADFAST", c: "Unwavering in practice"}, { w: "STOIC",     c: "Calm under pressure"  },
    ],
  },

  ocean: {
    name: "Ocean", icon: "fas fa-water", unlockAt: 60,
    words: [
      { w: "SEA",       c: "Salty expanse"         }, { w: "BAY",       c: "Calm inlet"           },
      { w: "EEL",       c: "Slithering fish"       }, { w: "RAY",       c: "Flat fish"            },
      { w: "FIN",       c: "Steering blade"        }, { w: "COD",       c: "Atlantic fish"        },
      { w: "KOI",       c: "Ornamental fish"       }, { w: "ROE",       c: "Fish eggs"            },
      { w: "ABYSS",     c: "Ocean deepest zone"    }, { w: "ALGA",      c: "Simple sea plant"     },
      { w: "ATOLL",     c: "Coral island ring"     }, { w: "BANK",      c: "Shallow water rise"   },
      { w: "BASS",      c: "Popular sport fish"    }, { w: "BILGE",     c: "Ship bottom water"    },
      { w: "BRINE",     c: "Very salty water"      }, { w: "BUOY",      c: "Floating marker"      },
      { w: "CAPE",      c: "Land point into sea"   }, { w: "CAVE",      c: "Underwater hollow"    },
      { w: "CLAM",      c: "Bivalve filter"        }, { w: "COVE",      c: "Sheltered bay"        },
      { w: "CRAB",      c: "Sidewalk walker"       }, { w: "CREST",     c: "Wave top"             },
      { w: "DEEP",      c: "Ocean trench zone"     }, { w: "DRIFT",     c: "Ocean wandering"      },
      { w: "EDDY",      c: "Circular current"      }, { w: "FISH",      c: "Cold-blooded swimmer" },
      { w: "FOAM",      c: "Wave froth"            }, { w: "GILL",      c: "Breathing organ"      },
      { w: "GULL",      c: "Shore bird"            }, { w: "GULF",      c: "Large sea inlet"      },
      { w: "GYRE",      c: "Ocean spiral system"   }, { w: "HULL",      c: "Boat body"            },
      { w: "KELP",      c: "Giant sea forest"      }, { w: "KNOT",      c: "Nautical speed unit"  },
      { w: "KRILL",     c: "Whale food"            }, { w: "MAST",      c: "Sail pole"            },
      { w: "MUSSEL",    c: "Blue shell bivalve"    }, { w: "OYSTER",    c: "Pearl maker"          },
      { w: "PIER",      c: "Sea walkway"           }, { w: "PORT",      c: "Harbour side"         },
      { w: "PRAWN",     c: "Small sea shrimp"      }, { w: "REEF",      c: "Coral wall"           },
      { w: "RIPPLE",    c: "Small wave"            }, { w: "SAND",      c: "Shore grains"         },
      { w: "SEABED",    c: "Ocean floor"           }, { w: "SEAL",      c: "Flippered mammal"     },
      { w: "SHOAL",     c: "Shallow fish zone"     }, { w: "SHORE",     c: "Water meets land"     },
      { w: "SHRIMP",    c: "Small crustacean"      }, { w: "SILT",      c: "Fine sea floor mud"   },
      { w: "SKATE",     c: "Flat cartilage fish"   }, { w: "SPONGE",    c: "Filter feeder"        },
      { w: "SPRAY",     c: "Wind-blown water"      }, { w: "SQUID",     c: "Ink jet swimmer"      },
      { w: "STERN",     c: "Boat back end"         }, { w: "SURGE",     c: "Powerful wave push"   },
      { w: "SWELL",     c: "Rolling ocean wave"    }, { w: "TIDE",      c: "Moon-pulled water"    },
      { w: "TRAWL",     c: "Net fishing drag"      }, { w: "TRENCH",    c: "Deepest ocean cut"    },
      { w: "TSUNAMI",   c: "Seismic ocean wave"    }, { w: "TUNA",      c: "Fast blue water fish" },
      { w: "URCHIN",    c: "Spiny sea ball"        }, { w: "VESSEL",    c: "Water craft"          },
      { w: "WAKE",      c: "Ship trail"            }, { w: "WALRUS",    c: "Tusked sea mammal"    },
      { w: "WAVE",      c: "Water motion"          }, { w: "WINKLE",    c: "Tiny sea snail"       },
      { w: "WRASSE",    c: "Reef cleaner fish"     }, { w: "BARNACLE",  c: "Rock clinging shell"  },
      { w: "BENTHIC",   c: "Ocean floor zone"      }, { w: "BRACKISH",  c: "Partly salty water"   },
      { w: "CETACEAN",  c: "Whale and dolphin"     }, { w: "CORAL",     c: "Reef builder"         },
      { w: "DOLPHIN",   c: "Playful swimmer"       }, { w: "ESTUARY",   c: "River meets sea"      },
      { w: "FJORD",     c: "Sea-flooded valley"    }, { w: "FLOTSAM",   c: "Floating wreck debris"},
      { w: "GROTTO",    c: "Sea cave pool"         }, { w: "JETSAM",    c: "Thrown cargo"         },
      { w: "LAGOON",    c: "Calm coastal pool"     }, { w: "LAMPREY",   c: "Jawless parasite"     },
      { w: "LEVIATHAN", c: "Sea monster legend"    }, { w: "MANGROVE",  c: "Root-in-water tree"   },
      { w: "MANATEE",   c: "Gentle sea cow"        }, { w: "NAUTILUS",  c: "Shell spiral swimmer" },
      { w: "NEAP",      c: "Weakest tide"          }, { w: "OCTOPUS",   c: "Eight-armed thinker"  },
      { w: "PORPOISE",  c: "Small cetacean"        }, { w: "SALINITY",  c: "Ocean saltiness"      },
      { w: "SCALLOP",   c: "Fan-shaped bivalve"    }, { w: "SONAR",     c: "Sound navigation"     },
      { w: "STINGRAY",  c: "Flat ocean glider"     }, { w: "SUBMARINE", c: "Underwater vessel"    },
      { w: "TIDEPOOL",  c: "Rock pool world"       }, { w: "UPWELLING", c: "Cold water rising"    },
      { w: "VORTEX",    c: "Ocean spinning mass"   }, { w: "WHALESHARK",c: "Biggest fish"         },
      { w: "WHITECAP",  c: "Breaking wave top"     }, { w: "WRACK",     c: "Beached seaweed"      },
      { w: "ABYSSAL",   c: "Deepest ocean plain"   }, { w: "PELAGIC",   c: "Open ocean zone"      },
      { w: "LIMPET",    c: "Clinging shell snail"  }, { w: "LITTORAL",  c: "Shore zone"           },
      { w: "MAELSTROM", c: "Violent whirlpool"     }, { w: "NAUTICAL",  c: "Sea related"          },
      { w: "PLANKTON",  c: "Microscopic drifters"  }, { w: "SEAGRASS",  c: "Underwater meadow"    },
      { w: "SEAHORSE",  c: "Upright swimmer"       }, { w: "SEAMOUNT",  c: "Underwater mountain"  },
      { w: "SEASHELL",  c: "Mollusc home"          }, { w: "STARFISH",  c: "Five-armed creature"  },
      { w: "SEABIRD",   c: "Ocean flier"           }, { w: "SCHOONER",  c: "Sailing vessel"       },
      { w: "CURRENT",   c: "Directional flow"      }, { w: "TURBID",    c: "Murky sea water"      },
      { w: "UNDERTOW",  c: "Pulling back current"  }, { w: "WHIRLPOOL", c: "Spinning water"       },
      { w: "WATERLINE", c: "Where hull meets sea"  }, { w: "INTERTIDAL",c: "Between tide zone"    },
      { w: "SEAWATER",  c: "Salt-laden ocean"      }, { w: "SEACLIFF",  c: "Coastal rock face"    },
      { w: "SEAFLOOR",  c: "Bottom of the ocean"   }, { w: "SEASCAPE",  c: "Ocean view"           },
      { w: "TIDEMARK",  c: "High water line"       }, { w: "TIDEWATER", c: "Coastal flood water"  },
      { w: "FLATFISH",  c: "Bottom dwelling fish"  }, { w: "SANDBANK",  c: "Shallow sand ridge"   },
      { w: "SANDBAR",   c: "Shore sand pile"       }, { w: "BEACHHEAD", c: "Shore landing point"  },
      { w: "ANEMONE",   c: "Tentacled sea flower"  }, { w: "BALLAST",   c: "Ship stability weight"},
      { w: "BATHYAL",   c: "Mid-depth ocean zone"  }, { w: "BEACON",    c: "Navigation light"     },
      { w: "BLOWHOLE",  c: "Whale breathing vent"  }, { w: "BOWSPRIT",  c: "Forward ship pole"    },
      { w: "BYCATCH",   c: "Unintended catch"      }, { w: "CAPSIZE",   c: "Boat overturning"     },
      { w: "CARTILAGE", c: "Shark skeleton material"}, { w: "CHANNEL",  c: "Navigable water lane" },
      { w: "CHARTER",   c: "Hired sea voyage"      }, { w: "CHROMIS",   c: "Reef damselfish"      },
      { w: "COBALT",    c: "Deep ocean blue"       }, { w: "COMPASS",   c: "Navigation direction" },
      { w: "CRUSTACEAN",c: "Shell-armored sea life" }, { w: "CYCLONE",  c: "Ocean storm system"   },
      { w: "DEADHEAD",  c: "Submerged floating log" }, { w: "DEEPDIVE",  c: "Going to depths"     },
      { w: "DINGHY",    c: "Small open boat"       }, { w: "DROGUE",    c: "Sea anchor drag"      },
      { w: "DREDGE",    c: "Seabed scooping"       }, { w: "DROMOND",   c: "Ancient oared ship"   },
      { w: "DUNE",      c: "Seafloor sand mound"   }, { w: "FAUNA",     c: "Ocean animal life"    },
      { w: "FENDER",    c: "Boat bumper pad"       }, { w: "FISHFARM",  c: "Aquaculture site"     },
      { w: "GALLEY",    c: "Oared warship"         }, { w: "GANGWAY",   c: "Ship boarding path"   },
      { w: "GROYNE",    c: "Shore erosion barrier" }, { w: "GUNWALE",   c: "Top edge of hull"     },
      { w: "HALYARD",   c: "Rope for raising sail" }, { w: "HARBOUR",   c: "Sheltered port"       },
      { w: "HAUL",      c: "Fish catch amount"     }, { w: "HEADWAY",   c: "Forward ship speed"   },
      { w: "HERRING",   c: "Schooling silver fish" }, { w: "HOLDFAST",  c: "Kelp anchor organ"    },
      { w: "HYDROTHERMAL",c:"Deep vent heat source"}, { w: "INLET",     c: "Narrow water gap"     },
      { w: "ISLET",     c: "Very small island"     }, { w: "JETTY",     c: "Stone pier structure" },
      { w: "KEYSTONE",  c: "Species that shapes reef"}, { w: "LARBOARD", c: "Old word for port"   },
      { w: "LEEWAY",    c: "Wind-caused drift"     }, { w: "LONGLINE",  c: "Deep sea fishing line"},
      { w: "LOOKOUT",   c: "Ship watch post"       }, { w: "LURE",      c: "Fishing bait device"  },
      { w: "MACKEREL",  c: "Striped fast fish"     }, { w: "MARINA",    c: "Small boat harbour"   },
      { w: "MARLIN",    c: "Billfish ocean leaper" }, { w: "MIDWATER",  c: "Open column ocean"    },
      { w: "MINNOW",    c: "Tiny river fish"       }, { w: "MOONFISH",  c: "Disc-shaped pelagic"  },
      { w: "NARROWS",   c: "Tight sea passage"     }, { w: "NETTING",   c: "Mesh fishing gear"    },
      { w: "OFFSHORE",  c: "Away from shore"       }, { w: "ONSHORE",   c: "Toward the shore"     },
      { w: "OUTRIGGER", c: "Balance float on side" }, { w: "PILCHARD",  c: "Small oil-rich fish"  },
      { w: "PINNACLE",  c: "Submerged rock spire"  }, { w: "RUDDER",    c: "Steering underwater fin"},
      { w: "SEAPLANE",  c: "Water landing aircraft"}, { w: "SEAMILE",   c: "Ocean distance unit"  },
      { w: "SMOLT",     c: "Young salmon stage"    }, { w: "SPAWN",     c: "Fish egg laying"      },
      { w: "SPRAT",     c: "Tiny schooling fish"   }, { w: "SQUALL",    c: "Sudden sea storm"     },
      { w: "STARBOARD", c: "Right side of ship"    }, { w: "SUBMERGE",  c: "Going under water"    },
      { w: "SURF",      c: "Breaking shore wave"   }, { w: "SWELLS",    c: "Open ocean rolling"   },
    ],
  },

  seasons: {
    name: "Seasons", icon: "fas fa-sun", unlockAt: 75,
    words: [
      { w: "BUD",       c: "Opening flower"        }, { w: "FOG",       c: "Low cloud"            },
      { w: "ICY",       c: "Frozen surface"        }, { w: "WET",       c: "Rainy days"           },
      { w: "HOT",       c: "Summer heat"           }, { w: "RAW",       c: "Bitter cold"          },
      { w: "DRY",       c: "No rain period"        }, { w: "MUD",       c: "Spring soft ground"   },
      { w: "DEW",       c: "Cool night drops"      }, { w: "BARE",      c: "Winter stripped tree" },
      { w: "BITE",      c: "Frost sharpness"       }, { w: "BLOOM",     c: "Spring flowering"     },
      { w: "BLOW",      c: "Autumn gusting wind"   }, { w: "CHILL",     c: "Cold air feeling"     },
      { w: "COAT",      c: "Winter outer layer"    }, { w: "COLD",      c: "Winter temperature"   },
      { w: "COOL",      c: "Autumn breeze"         }, { w: "CROP",      c: "Harvest bounty"       },
      { w: "DAWN",      c: "Summer early rising"   }, { w: "DECAY",     c: "Autumn dying"         },
      { w: "DRIP",      c: "Spring melt sound"     }, { w: "DUSK",      c: "Long winter dark"     },
      { w: "DUST",      c: "Dry summer ground"     }, { w: "FADE",      c: "Autumn leaf color"    },
      { w: "FALL",      c: "Autumn season name"    }, { w: "FIRE",      c: "Autumn color burst"   },
      { w: "FLAKE",     c: "Snow crystal"          }, { w: "FLOOD",     c: "Spring rain overflow" },
      { w: "FROST",     c: "Ice on morning grass"  }, { w: "GOLDEN",    c: "Autumn color palette" },
      { w: "GRASS",     c: "Spring green return"   }, { w: "GUST",      c: "Autumn strong blast"  },
      { w: "HAIL",      c: "Frozen rain balls"     }, { w: "HARVEST",   c: "Autumn bounty time"   },
      { w: "HEAT",      c: "Summer intensity"      }, { w: "HUMID",     c: "Sticky summer air"    },
      { w: "ICICLE",    c: "Hanging frozen drip"   }, { w: "LEAVES",    c: "Autumn carpet color"  },
      { w: "LIGHT",     c: "Long summer days"      }, { w: "MELT",      c: "Spring snow release"  },
      { w: "MIST",      c: "Morning low cloud"     }, { w: "MILD",      c: "Spring temperature"   },
      { w: "MONSOON",   c: "Heavy season rain"     }, { w: "MUGGY",     c: "Hot humid summer day" },
      { w: "NUMB",      c: "Cold finger feeling"   }, { w: "PETAL",     c: "Spring falling beauty"},
      { w: "PINE",      c: "Winter evergreen"      }, { w: "POLLEN",    c: "Spring allergy cloud" },
      { w: "PUDDLE",    c: "After rain pool"       }, { w: "RAIN",      c: "Falling water drops"  },
      { w: "REBIRTH",   c: "Spring renewal"        }, { w: "ROBIN",     c: "Spring herald bird"   },
      { w: "RUSTLE",    c: "Dry leaf sound"        }, { w: "SCARLET",   c: "Autumn maple hue"     },
      { w: "SEED",      c: "Spring potential"      }, { w: "SHIMMER",   c: "Summer heat haze"     },
      { w: "SLEET",     c: "Ice rain mix"          }, { w: "SLUSH",     c: "Melting dirty snow"   },
      { w: "SOWING",    c: "Spring planting time"  }, { w: "SPRING",    c: "First warm season"    },
      { w: "SQUALL",    c: "Sudden rain storm"     }, { w: "SUMMER",    c: "Hottest season"       },
      { w: "SUNBURN",   c: "Too much sun"          }, { w: "SUNRISE",   c: "Early summer dawn"    },
      { w: "SUNSET",    c: "Autumn golden close"   }, { w: "SWELTER",   c: "Extreme summer heat"  },
      { w: "THAW",      c: "Ice becoming water"    }, { w: "THUNDER",   c: "Summer storm sound"   },
      { w: "TWILIGHT",  c: "Between day and night" }, { w: "WARMTH",    c: "Spring coming back"   },
      { w: "WINTER",    c: "Coldest dark season"   }, { w: "EQUINOX",   c: "Equal day and night"  },
      { w: "BLIZZARD",  c: "Heavy snowstorm"       }, { w: "BLOSSOM",   c: "Spring tree flower"   },
      { w: "CROCUS",    c: "First spring flower"   }, { w: "DAFFODIL",  c: "Yellow spring trumpet" },
      { w: "DAYLIGHT",  c: "Hours of sun"          }, { w: "DORMANT",   c: "Winter sleeping plant" },
      { w: "DRIZZLE",   c: "Light gentle rain"     }, { w: "DROUGHT",   c: "Long dry spell"       },
      { w: "EVERGREEN", c: "Never loses leaves"    }, { w: "FROSTBITE", c: "Cold skin damage"     },
      { w: "GERMINATE", c: "Seed starting growth"  }, { w: "HIBERNATE", c: "Winter animal sleep"  },
      { w: "HURRICANE", c: "Season storm giant"    }, { w: "MIGRATION", c: "Season following birds"},
      { w: "PERENNIAL", c: "Returns every year"    }, { w: "SNOWFLAKE", c: "Unique ice crystal"   },
      { w: "SNOWSTORM", c: "Winter whiteout"       }, { w: "SOLSTICE",  c: "Longest or shortest day"},
      { w: "SUNFLOWER", c: "Summer face-turner"    }, { w: "TORRID",    c: "Intensely hot zone"   },
      { w: "TROPICAL",  c: "Year-round warmth"     }, { w: "VERDANT",   c: "Spring green lush"    },
      { w: "AUTUMNAL",  c: "Of the fall season"    }, { w: "CANOPY",    c: "Summer leaf cover"    },
      { w: "OVERCAST",  c: "Grey winter sky"       }, { w: "FLURRY",    c: "Quick snow burst"     },
      { w: "FROZEN",    c: "Winter locked solid"   }, { w: "WITHERED",  c: "Autumn dying plant"   },
      { w: "SNOWDRIFT", c: "Wind-piled snow"       }, { w: "SPRINGTIME",c: "Season of blooming"   },
      { w: "TRANSITION",c: "Between two seasons"   }, { w: "YELLOWING", c: "Autumn leaf shift"    },
      { w: "WINDY",     c: "Autumn characteristic" }, { w: "FOGGY",     c: "Low visibility day"   },
      { w: "SUNNY",     c: "Clear summer day"      }, { w: "BALMY",     c: "Pleasantly warm"      },
      { w: "BRISK",     c: "Cool energizing air"   }, { w: "CRISP",     c: "Sharp autumn air"     },
      { w: "CHILLY",    c: "Uncomfortably cold"    }, { w: "FROSTY",    c: "Covered in frost"     },
      { w: "OPPRESSIVE",c: "Humid and heavy air"   }, { w: "PARCHED",   c: "Dried out by heat"    },
      { w: "WINTRY",    c: "Cold and snowy"        }, { w: "STORMY",    c: "Rain and wind"        },
      { w: "SULTRY",    c: "Hot and humid"         }, { w: "BARREN",    c: "Empty winter field"   },
      { w: "RIPENING",  c: "Fruit growing full"    }, { w: "BUDDING",   c: "Early spring growth"  },
      { w: "SHEDDING",  c: "Autumn leaf dropping"  }, { w: "THAWING",   c: "Ice slowly melting"   },
      { w: "WARMING",   c: "Temperature rising"    }, { w: "COOLING",   c: "Temperature falling"  },
      { w: "GREENING",  c: "Spring color return"   }, { w: "BROWNING",  c: "Autumn grass drying"  },
      { w: "FROSTING",  c: "Thin ice forming"      }, { w: "MELTING",   c: "Snow becoming water"  },
      { w: "ARID",      c: "Extremely dry"         }, { w: "AMBER",     c: "Autumn golden tone"   },
      { w: "ANNUAL",    c: "Happening each year"   }, { w: "ANOMALY",   c: "Unusual weather event" },
      { w: "ARCTIC",    c: "Polar cold region"     }, { w: "ARIDITY",   c: "Dryness measure"      },
      { w: "ASTER",     c: "Autumn blooming flower" }, { w: "CYCLICAL",  c: "Repeating in pattern" },
      { w: "AZALEA",    c: "Spring shrub blossom"  }, { w: "BLANKET",   c: "Snow covering"        },
      { w: "BLEAK",     c: "Harsh winter feeling"  }, { w: "BLUSTERY",  c: "Windy and cold"       },
      { w: "BOUNTY",    c: "Autumn harvest plenty" }, { w: "CARDINAL",  c: "Winter red bird"      },
      { w: "CHERRY",    c: "Spring blossom tree"   }, { w: "CHRYSALIS", c: "Spring transformation"},
      { w: "CLOUDBANK", c: "Mass of clouds"        }, { w: "COBWEB",    c: "Autumn morning dew web"},
      { w: "DAISY",     c: "Simple spring flower"  }, { w: "DAMP",      c: "Slightly wet from rain"},
      { w: "DECIDUOUS", c: "Seasonal leaf shedder" }, { w: "DRENCHED",  c: "Soaked through"       },
      { w: "ELDERBERRY",c: "Autumn dark berry"     }, { w: "EQUATORIAL",c: "No real seasons zone" },
      { w: "ESTIVAL",   c: "Of the summer season"  }, { w: "DESCEND",   c: "Leaves coming down"   },
      { w: "FALLOW",    c: "Resting winter field"  }, { w: "FEN",       c: "Rainy season wetland" },
      { w: "FESTIVE",   c: "Winter celebration"    }, { w: "FLOODWATER",c: "Overflow rain water"  },
      { w: "FORSYTHIA", c: "Early yellow spring"   }, { w: "FRIGID",    c: "Extremely cold"       },
      { w: "GATHERING", c: "Harvest time act"      }, { w: "GELID",     c: "Ice-cold"             },
      { w: "GLACIAL",   c: "Ice age cold"          }, { w: "GLOOM",     c: "Dark winter days"     },
      { w: "GOLDENROD", c: "Late summer yellow"    }, { w: "HAWTHORN",  c: "Spring white blossom" },
      { w: "HAYMAKING", c: "Summer grass cutting"  }, { w: "HIBERNAL",  c: "Of the winter season" },
      { w: "HOARFROST", c: "White crystal frost"   }, { w: "HONEYBEE",  c: "Summer pollinator"    },
      { w: "ICE CAP",   c: "Polar frozen layer"    }, { w: "IDYLLIC",   c: "Perfect summer day"   },
      { w: "IRONWEED",  c: "Late purple bloomer"   }, { w: "JASMINE",   c: "Summer fragrant vine" },
      { w: "LAVENDER",  c: "Summer purple bloom"   }, { w: "LEAFFALL",  c: "Autumn shedding time" },
      { w: "LEAFMOULD", c: "Decomposed leaf layer" }, { w: "LENTEN",    c: "Early spring season"  },
      { w: "LILAC",     c: "Spring purple cluster" }, { w: "LINGERING", c: "Long slow winter"     },
      { w: "MAPLE",     c: "Autumn color king"     }, { w: "MARIGOLD",  c: "Summer orange bloom"  },
      { w: "MIDSUMMER", c: "Peak of warm season"   }, { w: "MISTY",     c: "Covered in soft fog"  },
      { w: "NARCISSUS", c: "Spring trumpet flower" }, { w: "NESTING",   c: "Spring bird building" },
      { w: "NIGHTFALL", c: "Evening arriving early"},{ w: "OVERTURE",  c: "First spring sign"    },
      { w: "OVERWINTERED",c:"Survived the cold"    }, { w: "PASTORAL",  c: "Peaceful summer rural"},
      { w: "PERIGEAN",  c: "Strong tide period"    }, { w: "PLANTING",  c: "Spring garden work"   },
      { w: "POLAR",     c: "Extreme cold zone"     }, { w: "RAINY",     c: "Wet season"           },
      { w: "REAPING",   c: "Harvest cutting time"  }, { w: "SEASONAL",  c: "Belonging to a season"},
      { w: "SUMMITS",   c: "Peak summer moments"   }, { w: "SPRINGLIKE",c: "Warm and fresh feel"  },
      { w: "SUNLIT",    c: "Bathed in sunshine"    }, { w: "TEMPERATE", c: "Mild seasonal climate" },
    ],
  },

  mystical: {
    name: "Mystical", icon: "fas fa-moon", unlockAt: 88,
    words: [
      { w: "HEX",       c: "Spell cast"            }, { w: "ORB",       c: "Magic sphere"         },
      { w: "RUE",       c: "Magical herb"          }, { w: "RUNE",      c: "Ancient symbol"       },
      { w: "MAGE",      c: "Spell caster"          }, { w: "TOME",      c: "Spell book"           },
      { w: "ELF",       c: "Forest spirit"         }, { w: "FAE",       c: "Fairy folk"           },
      { w: "IMP",       c: "Small devil"           }, { w: "ANKH",      c: "Life symbol"          },
      { w: "AURA",      c: "Energy field"          }, { w: "BANE",      c: "Curse element"        },
      { w: "BIND",      c: "Spell tying"           }, { w: "BONE",      c: "Death magic tool"     },
      { w: "BREW",      c: "Potion making"         }, { w: "CAST",      c: "Spell throwing"       },
      { w: "CHARM",     c: "Enchanted item"        }, { w: "CLOAK",     c: "Invisibility garment" },
      { w: "COVEN",     c: "Witch gathering"       }, { w: "CURSE",     c: "Dark wish upon"       },
      { w: "DUSK",      c: "Witching hour start"   }, { w: "ECHO",      c: "Spirit voice"         },
      { w: "EMBER",     c: "Ritual fire remains"   }, { w: "ETHER",     c: "Spirit medium"        },
      { w: "FATE",      c: "Woven destiny"         }, { w: "FUME",      c: "Ritual smoke"         },
      { w: "GHOST",     c: "Lingering spirit"      }, { w: "GLYPH",     c: "Power symbol"         },
      { w: "GNOME",     c: "Earth spirit"          }, { w: "GOLEM",     c: "Animated clay"        },
      { w: "GROVE",     c: "Sacred tree circle"    }, { w: "HAUNT",     c: "Spirit lingering"     },
      { w: "INVOKE",    c: "Call spirit forth"     }, { w: "JINX",      c: "Minor bad luck spell" },
      { w: "KNELL",     c: "Doom bell toll"        }, { w: "LORE",      c: "Ancient knowledge"    },
      { w: "LUNAR",     c: "Moon magic"            }, { w: "LURK",      c: "Shadow hiding"        },
      { w: "MAGIC",     c: "Unseen power"          }, { w: "MIRROR",    c: "Soul gateway"         },
      { w: "MIST",      c: "Spirit veil"           }, { w: "OMEN",      c: "Dark sign"            },
      { w: "ORACLE",    c: "Future teller"         }, { w: "PACT",      c: "Dark agreement"       },
      { w: "PHANTOM",   c: "Ghost apparition"      }, { w: "POTION",    c: "Magical drink"        },
      { w: "RELIC",     c: "Sacred old object"     }, { w: "RIFT",      c: "Between world crack"  },
      { w: "RITUAL",    c: "Sacred ceremony"       }, { w: "SACRED",    c: "Divine in nature"     },
      { w: "SCROLL",    c: "Ancient spell page"    }, { w: "SEAL",      c: "Binding symbol"       },
      { w: "SEANCE",    c: "Spirit calling"        }, { w: "SHADOW",    c: "Dark power source"    },
      { w: "SIGIL",     c: "Charged symbol"        }, { w: "SIREN",     c: "Dangerous enchanter"  },
      { w: "SKULL",     c: "Death power vessel"    }, { w: "SPECTER",   c: "Ghostly vision"       },
      { w: "SPELL",     c: "Spoken magic"          }, { w: "SPIRIT",    c: "Non-physical being"   },
      { w: "SPRITE",    c: "Nature fairy spirit"   }, { w: "STAFF",     c: "Wizard channel"       },
      { w: "SUMMON",    c: "Call from beyond"      }, { w: "SYLPH",     c: "Air elemental"        },
      { w: "TAROT",     c: "Fortune cards"         }, { w: "TOKEN",     c: "Magical object"       },
      { w: "TOTEM",     c: "Spirit animal carving" }, { w: "TRANCE",    c: "Spirit journey state" },
      { w: "UNDEAD",    c: "Risen from death"      }, { w: "VEIL",      c: "Between world thin"   },
      { w: "VESSEL",    c: "Spirit container"      }, { w: "VISION",    c: "Prophetic sight"      },
      { w: "VOODOO",    c: "Spirit doll magic"     }, { w: "WAND",      c: "Magic focusing tool"  },
      { w: "WARD",      c: "Protective barrier"    }, { w: "WARLOCK",   c: "Male dark mage"       },
      { w: "WEAVE",     c: "Spell threading"       }, { w: "WITCH",     c: "Magic practitioner"   },
      { w: "WIZARD",    c: "Learned mage"          }, { w: "WRAITH",    c: "Undead spirit"        },
      { w: "WYVERN",    c: "Two-legged dragon"     }, { w: "ARCANE",    c: "Secret knowledge"     },
      { w: "BANSHEE",   c: "Wailing death spirit"  }, { w: "BASILISK",  c: "Stone gaze creature"  },
      { w: "BESTIARY",  c: "Monster record book"   }, { w: "CAULDRON",  c: "Brewing vessel"       },
      { w: "CELESTIAL", c: "Sky realm being"       }, { w: "CHIMERA",   c: "Mixed beast creature" },
      { w: "CRYPT",     c: "Undead resting place"  }, { w: "DRUID",     c: "Nature spell keeper"  },
      { w: "ENCHANTED", c: "Under magic spell"     }, { w: "FAMILIAR",  c: "Witch spirit animal"  },
      { w: "GARGOYLE",  c: "Stone guardian"        }, { w: "GRIFFIN",   c: "Lion eagle hybrid"    },
      { w: "HELLFIRE",  c: "Dark flame power"      }, { w: "LABYRINTH", c: "Magic maze puzzle"    },
      { w: "LEVIATHAN", c: "Sea chaos monster"     }, { w: "MOONSTONE", c: "Luna magic gem"       },
      { w: "NECROMANCY",c: "Dead raising magic"    }, { w: "OUROBOROS", c: "Snake eating itself"  },
      { w: "PENTAGRAM", c: "Five-point star seal"  }, { w: "POLTERGEIST",c:"Noisy ghost"          },
      { w: "PROPHECY",  c: "Foretold future"       }, { w: "SORCERER",  c: "Power born mage"      },
      { w: "TALISMAN",  c: "Lucky charm object"    }, { w: "UNDERWORLD",c: "Realm of the dead"    },
      { w: "UNICORN",   c: "Horn-blessed horse"    }, { w: "GRIMOIRE",  c: "Spell record book"    },
      { w: "SOOTHSAYER",c: "Truth speaker"         }, { w: "MOONSONG",  c: "Lunar chant"          },
      { w: "KEENING",   c: "Spirit death wail"     }, { w: "ENCHANT",   c: "Magic weaving"        },
      { w: "KARMA",     c: "Cosmic consequence"    }, { w: "SYMBOL",    c: "Hidden meaning mark"  },
      { w: "POWER",     c: "Raw magical force"     }, { w: "TWILIGHT",  c: "Veil between worlds"  },
      { w: "STYGIAN",   c: "Dark underworld hue"   }, { w: "TEMPEST",   c: "Magic storm"          },
      { w: "DRAGON",    c: "Fire-breathing beast"  }, { w: "PHOENIX",   c: "Reborn from ashes"    },
      { w: "KRAKEN",    c: "Sea monster legend"    }, { w: "VALKYRIE",  c: "Battle chooser"       },
      { w: "MINOTAUR",  c: "Bull-headed beast"     }, { w: "CERBERUS",  c: "Three-headed hound"   },
      { w: "MEDUSA",    c: "Stone-gaze woman"      }, { w: "CYCLOPS",   c: "One-eyed giant"       },
      { w: "GOBLIN",    c: "Mischievous creature"  }, { w: "OGRE",      c: "Brutish monster"      },
      { w: "APPARITION",c: "Ghostly presence form" }, { w: "NIXIE",     c: "Water spirit"         },
      { w: "SYLVAN",    c: "Forest magical being"  }, { w: "AMULET",    c: "Protective ornament"  },
      { w: "TETHER",    c: "Binding magical link"  }, { w: "INFERNAL",  c: "Of the underworld"    },
      { w: "SANCTUM",   c: "Sacred protected space" }, { w: "REVENANT", c: "Returned from death"  },
      { w: "DIVINATION",c: "Seeing future signs"   }, { w: "OBSIDIAN",  c: "Volcanic dark glass"  },
      { w: "ABYSMAL",   c: "Darkest depths"        }, { w: "ALCHEMY",   c: "Lead to gold magic"   },
      { w: "ALLURE",    c: "Magical attraction"    }, { w: "AMNESIA",   c: "Memory erasing curse" },
      { w: "ANIMISM",   c: "Spirit in all things"  }, { w: "PHANTASM",  c: "Ghostly illusion"     },
      { w: "ARTEFACT",  c: "Magical ancient object" }, { w: "ASTRAL",   c: "Spirit plane travel"  },
      { w: "AUGURY",    c: "Bird sign reading"     }, { w: "AVATAR",    c: "Divine incarnation"   },
      { w: "BARRIER",   c: "Magical wall"          }, { w: "BEWITCHED", c: "Under a spell"        },
      { w: "BINDING",   c: "Spell that locks"      }, { w: "BLIGHT",    c: "Disease curse"        },
      { w: "BLOODSTONE",c: "Healing power gem"     }, { w: "CLAIRVOYANT",c:"Clear-seeing one"     },
      { w: "COMMUNION", c: "Spirit connection act" }, { w: "CONJURE",   c: "Summoning magic"      },
      { w: "CRYSTAL",   c: "Energy focusing stone" }, { w: "DAEMON",    c: "Guiding spirit"       },
      { w: "DAGGER",    c: "Ritual cutting tool"   }, { w: "DEMON",     c: "Dark spirit being"    },
      { w: "DEMONOLOGY",c: "Study of dark spirits" }, { w: "DOWSING",   c: "Water finding magic"  },
      { w: "EFFIGY",    c: "Spell figure image"    }, { w: "ELIXIR",    c: "Magical liquid"       },
      { w: "ENCHANTER", c: "Weaver of spells"      }, { w: "ENIGMA",    c: "Unsolvable mystery"   },
      { w: "ETHEREAL",  c: "Light otherworldly"    }, { w: "EXORCISM",  c: "Spirit removal rite"  },
      { w: "FABLE",     c: "Ancient magic story"   }, { w: "FEY",       c: "Fairy-touched"        },
      { w: "FIEND",     c: "Evil spirit entity"    }, { w: "FOLKLORE",  c: "Ancient magic tales"  },
      { w: "FORSAKEN",  c: "Cursed and abandoned"  }, { w: "GALDOR",    c: "Norse spoken spell"   },
      { w: "GLAMOUR",   c: "Illusion magic"        }, { w: "HALLOWED",  c: "Made sacred"          },
      { w: "HARBINGER", c: "Omen bearer"           }, { w: "HAUNTING",  c: "Ghost activity"       },
      { w: "HELLGATE",  c: "Portal to underworld"  }, { w: "HERETIC",   c: "Sacred law breaker"   },
      { w: "HEXAGRAM",  c: "Six-pointed seal"      }, { w: "IDOL",      c: "Worshipped object"    },
      { w: "ILLUSION",  c: "Not what it seems"     }, { w: "IMMORTAL",  c: "Cannot be killed"     },
      { w: "INCUBUS",   c: "Dream demon"           }, { w: "INFERNO",   c: "Magical fire place"   },
      { w: "INITIATE",  c: "New spell learner"     }, { w: "INVOKING",  c: "Calling upon power"   },
      { w: "WAILING",   c: "Mourning spirit cry"   }, { w: "LAIR",      c: "Monster dwelling"     },
      { w: "LAMIA",     c: "Snake-woman creature"  }, { w: "LEGEND",    c: "Ancient power tale"   },
      { w: "LYCANTHROPE",c:"Werewolf person"       }, { w: "MEGALITH",  c: "Standing stone magic" },
      { w: "MENHIR",    c: "Single standing stone" }, { w: "MOONWITCH", c: "Lunar magic user"     },
      { w: "NETHERWORLD",c:"Realm below living"    }, { w: "NIGHTSHADE",c: "Poisonous dark plant"  },
      { w: "OBELISK",   c: "Tall stone monument"   }, { w: "OCCULTISM", c: "Hidden knowledge study"},
    ],
  },
};